services:
  paywall:
    image: hidewall:latest
    ports:
      - "8070:80"
    restart: unless-stopped
    environment:
      - "USEVPN=false"
      - "USERNAME="
      - "PASSWORD="
      - "ENABLE_OTEL=false"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317"
    labels:
      - "traefik.http.routers.paywall.rule=Host(`hostname`)"
