version: "3"
services:
  paywall:
    image: astrognome/hidewall
    ports:
      - "8069:80"
    restart: unless-stopped
    environment:
      - "USEVPN=true"
      - "USERNAME="
      - "PASSWORD="
    labels:
      - "traefik.http.routers.paywall.rule=Host(`hostname`)"
