version: "3"
services:
  paywall:
    image: hidewall:dev
    ports:
      - "8070:80"
    restart: unless-stopped
    environment:
      - "USEVPN=false"
      - "USERNAME="
      - "PASSWORD="
    labels:
      - "traefik.http.routers.paywall.rule=Host(`hostname`)"
