version: "3"
services:
  paywall:
    image: my-google-cache-app
    ports:
      - "8069:80"
    restart: unless-stopped
    labels:
      - "traefik.http.routers.paywall.rule=Host(`paywall.starnix.net`)"
