services:
  paywall:
    image: astrognome/hidewall:latest
    ports:
      - "8069:80"
    restart: unless-stopped
    environment:
      - "ENABLE_OTEL=false"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317"
    labels:
      - "traefik.http.routers.paywall.rule=Host(`hostname`)"
